notes = "Pre release"
name = "malef"
description = "Library to develop Terminal User Interface toolkit"
long-description = """Malef is a library to develop Terminal User Interfaces in
Ada. It is similar to Ncurses, but everything is built from the ground-up in
Ada without any dependencies. It provides a very simple interface for building
Applications using Widgets and for creating your own Widgets. It is cross
compatible it should work on the old Windows' CMD and on ANSI compatiable
terminals.
"""
version = "0.4.0"

authors = ["José Antonio Verde Jiménez <joseaverde@protonmail.com>"]
maintainers = ["José Antonio Verde Jiménez <joseaverde@protonmail.com>"]
maintainers-logins = ["joseaverde"]


licenses = "GPL-3.0-or-later"
website = "https://github.com/joseaverde/Malef"
tags = ["sdk", "ansi", "terminal", "console", "tui", "interfaces"]


# Information about package's inside.
project-files = ["malef.gpr"]


# We map the names of external variables in the .gpr project file.
[gpr-externals]
MALEF_SYSTEM         = ["linux", "windows", "unix"]
MALEF_SUBSYSTEM      = ["ansi", "cmd"]

# How to built it depends on the operating system.
[gpr-set-externals.'case(os)']
'linux' = { MALEF_OPERATING_SYSTEM = "linux" }
'windows' = { MALEF_OPERATING_SYSTEM = "win64" }
'...' = { MALEF_OPERATING_SYSTEM = "unix" }

[configuration]
generate_c = false

[build-switches]
release.optimization   = "Performance"
release.debug_info     = "No"
release.runtime_checks = "None"
release.compile_checks = "None"
release.contracts      = "Yes"
release.style_checks   = "No"
release.ada_version    = "Ada2022"

development.optimization   = "Debug"
development.debug_info     = "Yes"
development.runtime_checks = "Everything"
development.compile_checks = "Warnings"
development.contracts      = "Yes"
development.style_checks   = "Yes"
development.ada_version    = "Ada2022"

validation.optimization   = "Performance"
validation.debug_info     = "Yes"
validation.runtime_checks = "Everything"
validation.compile_checks = "Errors"
validation.contracts      = "Yes"
validation.style_checks   = "Yes"
validation.ada_version    = "Ada2022"
