#!/usr/bin/env  python3
# *-* encoding=utf8 *-*

import malef

surface = malef.Surface (2, 16)

def getColor ( colour ) :
    return malef.getPalette ()[colour]

malef.initialize ()
malef.newPage ()


for pal in malef.palettes:
    col = 1
    malef.setPalette (pal)
    for colour in malef.colors:
        surface.setForeground (getColor (colour), 1, col)
        surface.setBackground (getColor (colour), 2, col)
        col += 1
    surface.debugPut ()
    input ()

malef.finalize ()
