--  Configuration for malef generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Malef_Config is
   pragma Pure;

   Crate_Version : constant String := "0.3.0";
   Crate_Name : constant String := "malef";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "arch";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Malef_Config;
